---
title: "S2"
author: "Jair Andrade"
date: '2023-05-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(ggplot2)
library(patchwork)
library(pomp)
library(purrr)
library(readr)
library(readsdr)
library(stringr)
library(tictoc)
library(tidyr)

source("./R_scripts/plots.R")
source("./R_scripts/R0_estimation.R")

pop_val <- 17475415

beta_vals <- 0.724637681 * c(1, 1.5, 2)
```

```{r}
bio_df <- read_csv("./Data/bio_params.csv", 
                       show_col_types = FALSE)

bio_params        <- as.list(bio_df$Value)
names(bio_params) <- bio_df$Parameter
```


# Base case

```{r}
mdl <- read_xmile("./models/01_SEI3R.stmx", const_list = bio_params)

par_beta_df <- data.frame(par_beta = beta_vals)

sens_df <- sd_sensitivity_run(mdl$deSolve_components, 
                              consts_df = par_beta_df,
                              integ_method = "euler", start_time = 0,
                              stop_time = 1000, timestep = 1 / 64,
                              multicore = TRUE, n_cores = 3) |> 
  mutate(c      = C / N,
         c_base = c,
         s      = S / N)
```

```{r}
base_df <- sens_df |> select(time, c_base, par_beta, s) |> 
  mutate(R0 = round(map_dbl(par_beta, estimate_R0, bio_params), 1),
         Rt = R0 * s) |> 
  filter(time - trunc(time) == 0)
```

```{r}
ggplot(base_df, aes(time, c_base)) +
  geom_line(aes(group = R0)) + 
  theme_classic()
```

```{r, warning = FALSE}
Rt_df <- base_df |> 
  mutate(diff_rt = abs(1 - Rt)) |> 
  group_by(R0) |> 
  filter(diff_rt == min(diff_rt))

ggplot(base_df, aes(time, Rt)) +
  geom_line(aes(group = R0, colour = as.factor(R0))) + 
  scale_x_continuous(limits = c(0, 120)) +
  geom_hline(yintercept = 1, linetype = "dotted", colour = "grey50") +
  theme_classic()
```

```{r}
set.seed(1550)

samples <- runif(997, beta_vals[[1]], beta_vals[[3]])
betas   <- c(samples, beta_vals) |> sort()

c_df <- data.frame(par_beta = betas)
```


```{r}
fn <- "./saved_objects/model_01_beta_sens.rds"

if(!file.exists(fn)) {
  
  wo_mort <- sd_sensitivity_run(mdl$deSolve_components, 
                              consts_df    = c_df,
                              integ_method = "rk4", start_time = 0,
                              stop_time    = 150, 
                              timestep     = 1 / 16,
                              multicore    = TRUE)
  
  SEI3R_df <- wo_mort |> select(time, C, iter, par_beta)
  
  saveRDS(SEI3R_df, fn)
   
} else SEI3R_df <- readRDS(fn)
```

```{r}
SEI3R_df <- SEI3R_df |>
  mutate(c     = C / pop_val,
         model = "SEI3R")
```


## Disease-inducing mortality

```{r}
mdl2 <- read_xmile("./models/01b_SEI3RD.stmx",
                  const_list = c(bio_params, 
                                 list(par_rho = 0.025)))
```

```{r}
fn <- "./saved_objects/model_01b_beta_sens.rds"

if(!file.exists(fn)) {
  
  mort_df <- sd_sensitivity_run(mdl2$deSolve_components, 
                              consts_df    = c_df,
                              integ_method = "rk4", start_time = 0,
                              stop_time    = 150, 
                              timestep     = 1 / 16,
                              multicore    = TRUE)
  
  SEI3RD_df <- mort_df |> select(time, C, iter, par_beta)
  
  saveRDS(SEI3RD_df, fn)
   
} else SEI3RD_df <- readRDS(fn)
```


```{r}
SEI3RD_df <- SEI3RD_df |>
  mutate(c  = C / pop_val,
         R0 = map_dbl(par_beta, estimate_R0, bio_params),
         model = "SEI3RD")
```


```{r}
df <- bind_rows(SEI3R_df, SEI3RD_df)

plot_fig_02(df) -> g

ggsave("./plots/Fig_02_Attack_rate.pdf", plot = g, 
       height = 4, width = 7)

g
```

```{r}
df2 <- df |> filter(time == 150)
df_list <- split(df2, df2$model)

ggplot(df2, aes(c)) +
  geom_histogram(aes(colour = model), fill = "white") +
  facet_wrap(~model, ncol = 1) +
  labs(x = parse(text = "'Attack rate at day 150'~(c[150])"),
       y = "Count") +
  theme_minimal()
```



# Vaccines

```{r}
vacc_path   <- "./models/02_Vaccines.stmx"
alpha_v_val <- 12.26
phi_val     <- 0.65 # Vaccine effectiveness
Qv0_val     <- 2.45
```

```{r}
n_sims <- 1e4

mdl       <- read_xmile(vacc_path, 
                        const_list = c(bio_params,
                                       par_alpha_v = 12.26,
                                       par_rho_v   = 0.15,
                                       par_phi     = 0.65),
                        stock_list = list(Qv = 2.45)) 
ds_inputs <- mdl$deSolve_components 
```

```{r}
avl_sens <- sd_sensitivity_run(ds_inputs, 
                               consts_df = data.frame(par_tau_v = c(60, 30, 15)),
                               start_time = 0,
                               stop_time = 150,
                               timestep = 1 / 64,
                               integ_method = "euler", multicore = TRUE,
                               n_cores = 3) |> 
  select(time, iter, par_tau_v, Vaccine_supply)
```

```{r}
set.seed(300)

sobol_design(lower = c(par_rho_v = 0, 
                       par_tau_v = 0),
             upper = c(par_rho_v = 0.3,
                       par_tau_v = 180),
             nseq = n_sims) -> consts_df
```

```{r}
plot(consts_df)
```


```{r}
lapply(beta_vals, \(beta_val, consts_df) {
  
  R0_val <- estimate_R0(beta_val, bio_params) |> round(1)
  
  fn <- str_glue({"./saved_objects/model_02_R0_{R0_val}.rds"})
  
  if(!file.exists(fn)) {
 
    tic()
    
    consts_df$par_beta <- beta_val
  
    sens <- sd_sensitivity_run(ds_inputs, consts_df, start_time = 0, 
                               stop_time = 300, timestep = 1 / 64,
                               integ_method = "euler", multicore = TRUE)
    toc()
    
    df <- sens |> select(time, iter, C, par_rho_v, par_tau_v, par_iota) |> 
      mutate(R0 = R0_val)
  
    saveRDS(df, fn) 
  } else {
    df <- readRDS(fn)
  }
  
  df
}, consts_df) -> sens_list
```

```{r}
sens_df <- bind_rows(sens_list)
```


```{r}
comp_df <- base_df |> 
  mutate(key = paste(time, R0, sep = "_")) |> 
  select(key, c_base)

sens_df <- sens_df |> 
  mutate(key = paste(time, R0, sep = "_")) |> 
  left_join(comp_df, by = "key") |> 
    mutate(c = C / pop_val,
         c_star = round(c / c_base, 3))
```

```{r}
R0_sens <- sens_df |> filter(time == 300) |> 
  select(R0, par_rho_v, par_tau_v, c, c_star, c_base) |> 
  mutate(R0_lbl = str_glue("\u211c[0]~'= {R0}'"))
```


## By willingness to vaccinate

```{r}
iotas <- c(0.2, 0.60, 1)
```

```{r}
lapply(iotas, \(iota_val) {
  
  mdl <- read_xmile(vacc_path, 
                  const_list = c(bio_params,
                                 par_alpha_v = 12.26,
                                 par_rho_v   = 0.15,
                                 par_phi     = 0.65,
                                 par_beta    = beta_vals[[2]]),
                  stock_list = list(Qv = 2.45,
                                    S  = pop_val * iota_val - 1,
                                    Sh = pop_val * (1 -  iota_val))) 
  
  ds_inputs <- mdl$deSolve_components 
  
  fn <- str_glue("./saved_objects/model_02_iota_{iota_val}.rds")
  
  if(!file.exists(fn)) {
  
    tic()
    out_sens <- sd_sensitivity_run(ds_inputs, consts_df,
                                   start_time   = 0, 
                                   stop_time    = 300,
                                   timestep     = 1 / 64,
                                   integ_method = "euler", 
                                   multicore = TRUE) |> 
      mutate(par_iota = iota_val)
    toc()
    
    results_df <- out_sens |> select(time, iter, par_beta, C, par_rho_v, 
                                     par_tau_v, par_iota)
  
    saveRDS(results_df, fn)
 
 } else results_df <- readRDS(fn)
  
  results_df
}) -> iota_sens
```


```{r}
sens_df <- bind_rows(iota_sens) |> 
  mutate(R0 = 3,
         key = paste(time, R0, sep = "_")) |> 
  left_join(comp_df, by = "key") |> 
    mutate(c = C / pop_val,
         c_star = round(c / c_base, 3)) 
```

```{r}
final_df <- sens_df |> filter(time == 300) |> 
  select(par_iota, par_rho_v, par_tau_v, c, c_star) |> 
  mutate(iota_lbl = str_glue("iota^v~'= {par_iota}'"))
```

```{r}
iota_val <- 1

mdl <- read_xmile(vacc_path, 
                  const_list = c(bio_params,
                                 par_alpha_v = 12.26,
                                 par_rho_v   = 0,
                                 par_phi     = 0.65,
                                 par_beta    = beta_vals[[2]],
                                 par_tau_v   = 15),
                  stock_list = list(Qv = 12.26,
                                    S  = pop_val * iota_val - 1,
                                    Sh = pop_val * (1 -  iota_val))) 
```

```{r}
out_df <- sd_simulate(mdl$deSolve_components, start_time = 0, stop_time = 300,
                      timestep = 1 / 64) |> 
  mutate(c = C / pop_val)
```

```{r}
rates_df <- out_df |> filter(time <= 90) |> 
  select(time, C_in, S_to_R) |> 
  rename(`Incidence rate` = C_in,
         `Vaccination rate` = S_to_R) |> 
  pivot_longer(-time, names_to = "variable")
```

```{r}
vacc_supp <- out_df |> filter(time <= 90) |> 
  select(time, Vaccine_supply, Vaccine_demand) |> 
    mutate(ratio = Vaccine_demand / Vaccine_supply)
```



```{r, dev='cairo_pdf', fig.height = 7, fig.width = 7}
g <- plot_fig_04(avl_sens, R0_sens, final_df, rates_df, vacc_supp)

ggsave("./plots/Fig_04_Vaccination_analysis.pdf", plot = g, 
       height = 7.5, width = 7, device = cairo_pdf)

g
```

## Ideal scenario

```{r}
mdl <- read_xmile(vacc_path, const_list = c(bio_params,
                                     par_alpha_v = alpha_v_val,
                                     par_rho_v   = 0,
                                     par_phi     = phi_val,
                                     par_iota    = 1,
                                     par_beta    = beta_vals[[2]],
                                     par_tau_v   = 15),
                        stock_list = list(Qv = alpha_v_val)) 
```

```{r}
sd_simulate(mdl$deSolve_components, start_time = 0, 
            stop_time = 1000, 
            timestep = 1 / 64, integ_method = "euler") |> 
  select(time, C) |> mutate(c = C/pop_val) |> filter(time == 300) |> 
  pull(c)
```
